/// Regenerates `src/rti.rs` from the `.proto` files in `src/raw-proto/`.
/// Run via: `cargo run --example generate_protos && cargo fmt`
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = std::path::PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").map_err(
        |_| "CARGO_MANIFEST_DIR not set — run this via `cargo run --example generate_protos`",
    )?);
    let src_dir = manifest_dir.join("src");
    let proto_dir = src_dir.join("raw-proto");

    let mut config = prost_build::Config::new();
    // Rithmic adds fields to existing messages in most template releases, so a
    // generated type without this makes every proto refresh a semver-major event here.
    config.type_attribute(".", "#[non_exhaustive]");
    config.out_dir(&src_dir);
    config.compile_protos(&[proto_dir.join("otps_proto_pool.proto")], &[&proto_dir])?;

    // MessageType is in a separate proto not referenced by the pool,
    // so we compile it separately and append it to the generated file.
    config.out_dir(std::env::temp_dir());
    config.compile_protos(&[proto_dir.join("message_type.proto")], &[&proto_dir])?;

    let message_type_code = std::fs::read_to_string(std::env::temp_dir().join("rti.rs"))?;

    // Read the pool-generated file, prepend `pub mod messages;` and append MessageType
    let pool_path = src_dir.join("rti.rs");
    let pool_code = std::fs::read_to_string(&pool_path)?;

    // Both halves are generated files, so both open with this line. Keep the one
    // `message_type_code` carries and drop the pool's, leaving a single header.
    const GENERATED_HEADER: &str = "// This file is @generated by prost-build.\n";
    let pool_body = pool_code
        .strip_prefix(GENERATED_HEADER)
        .ok_or("pool output does not start with the prost-build header")?;

    // Rithmic's vendored `.proto` files carry literal tabs in their trailing
    // comments, which prost copies into doc comments. Allow it at the module
    // level rather than editing the vendored protos, so the next refresh from
    // Rithmic does not reintroduce a clippy failure under `-D warnings`.
    let combined = format!(
        "#![allow(clippy::tabs_in_doc_comments)]\n\npub mod messages;\n\n{message_type_code}{pool_body}"
    );
    std::fs::write(&pool_path, combined)?;

    println!("Generated src/rti.rs — run `cargo fmt` to format it.");
    Ok(())
}
